name: Master
on: 
  push:
    branches: 
    - 'master'
jobs: 
  notify-slack:
    name: Notify Start Build
    runs-on: ubuntu-latest
    steps:
    - name: ChatOps w/ Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C014RMKG6H2\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

  image-vulnerability-scan:
    name: Image Vulnerability Scan 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Vulnerability Scan on Image w/ Trivy

    - name: Statically Analyze Config File (Dockerfile) w/ OPA Conftest

  build-upload-image:
    name: Build and Upload Image to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker_nodejs_demo
        IMAGE_TAG: nodejs_demo_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
  dev-cluster-vulnerability-scan:
    name: K8s Dev Cluster Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
    - name: Statically Analyze Config File (Manifest) w/ OPA Conftest

    - name: Dev Cluster Vulnerability Scan w/ Kubesec

  deploy-staging: 
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    steps:

