name: Pull Request
on: 
  pull:
    branches: 
    - 'master'
jobs: 
  code-analysis-sast:
    name: Execute Static Code Analysis - SAST
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: SAST w/ SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=devsecopsgithubactionsnodejsproject
          -Dsonar.projectKey=devsecopsganodejsprojectkey

  dependency-scan-sca:
    name: Dependency Scan - SCA
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: SCA w/ Snyk
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


