name: Build Test
on: 
  push:
    branches: 
    - '**'  
    - '!master'
    - '!release'
jobs: 
  notify-slack:
    name: Notify Start Build
    runs-on: ubuntu-latest
    steps:
    - name: ChatOps w/ Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C014RMKG6H2\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

  tests:
      name: Execute Tests
      runs-on: ubuntu-latest
      steps:
      - name: Checkout # basically clones your code from git repo to the runner/machine where this job run 
        uses: actions/checkout@v3

      - name: Node Setup - Install All Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          run: npm ci # install all exact version dependencies or devDependencies from a package-lock 
      
      - name: Run Unit Tests w/ Jest 
        run: npm test 

      - name: Run Mutation Tests w/ Stryker 
        run: npm run mutate 
